name: presnc_app
description: Versao inicial para apresentacao.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  qr_utils: ^0.1.4
  geolocator: ^3.0.1
  http: ^0.12.0+2
  localstorage: ^3.0.0+3
  path_provider: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf
